Classroom/urls.py
from django.urls import path
from . import views
from django.contrib.auth import views as auth_views

urlpatterns = [
    path('login/', auth_views.LoginView.as_view(template_name='login.html'),name='login'),
    path('classroom/', views.classroom, name='Classroom'),
    path('home/', views.Home, name='home'),
    path('register/', views.register, name='register'),
    path('logout/', auth_views.LogoutView.as_view(next_page='home'), name="logout"),
]

Classroom_Management/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('my_Class.urls')),
]

my_Class/urls.py
from django.urls import path
from . import views
from .views import CustomLoginView
from django.contrib.auth import views as auth_views
from django.contrib.auth.decorators import login_required
from django.contrib.auth.views import LogoutView


urlpatterns = [

    path('', CustomLoginView.as_view(template_name='login.html'), name='home'),
    path('option/', views.option_view, name='option'),
    path('classroom/',views.classroom_view , name='Classroom'),
    path('register/', views.register_view, name='register'),
    path('logout/', auth_views.LogoutView.as_view(next_page='home'), name="logout"),
    # details
    path('student/<int:student_ID>', views.student_detail, name='student_detail'),
    # 
    path('student_grade/<int:student_ID>', views.student_grade_view, name='student_grade_view'),
    path('reviewweekend/',views.week_summary_view , name='reviewweekend'),
    path('Savescore/',views.test_saveScore, name='Savescore'),
    
]

my_Class/models.py
from django.db import models
from django.contrib.auth.models import User
from django.core.exceptions import ValidationError



class Subject (models.Model):
    subject_CODE = models.CharField(primary_key=True, max_length = 10,unique=True)
    subject_name = models.CharField(max_length = 100)
    def __str__(self):
        return f"{self.subject_CODE}-{self.subject_name}"
    

    
class Teacher(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    teacher_ID = models.IntegerField(unique=True)
    subjects = models.ManyToManyField(Subject)
    def get_teacher_ID( self):
        return f"{self.teacher_ID}"
    def get_teacher_name( self):
        return f"{self.user.get_full_name()}"
    def __str__(self)->str:
        return f"{self.user.get_full_name()} - {self.teacher_ID}"

# ---------- Class Lớp học ----------    
class Class(models.Model):
    class_CODE = models.CharField(primary_key=True, max_length = 5)
    teacher = models.ForeignKey(Teacher,on_delete=models.CASCADE, blank=True, null=True)
    subjects = models.ManyToManyField(Subject)
    def __str__(self):
        return  f"{self.class_CODE}"
# ---------- Class student ----------
class Student(models.Model):
    student_ID = models.IntegerField(primary_key=True,auto_created=True)
    student_name = models.CharField(max_length=100)
    classroom = models.ForeignKey(Class, on_delete=models.CASCADE,blank=True, null=True)
    def __str__(self):
        return f"{self.student_name} - {self.student_ID}" 
# ---------- Class Điểm ----------     
class Score(models.Model):
    student = models.ForeignKey(Student, on_delete=models.CASCADE)
    subject= models.ForeignKey(Subject, on_delete=models.CASCADE)
    K1_score = models.FloatField(null=True, blank=True)
    K2_score = models.FloatField(null=True, blank=True)
    K3_score = models.FloatField(null=True, blank=True)
    def clean(self):
        if self.subject not in self.student.classroom.subjects.all():
            raise ValidationError("The selected subject is not one of the subjects that the student is studying.")

    
class Lessons (models.Model):
    classroom = models.ForeignKey(Class, on_delete=models.CASCADE)
    subject = models.ForeignKey(Subject, on_delete=models.CASCADE)
    teacher = models.ForeignKey(Teacher, on_delete=models.CASCADE)
    schedule_time = models.DateTimeField(auto_now_add=True)
    counter = models.PositiveIntegerField(default=1)  # Thêm trường counter

    def __str__(self):
        return f"{self.classroom} - {self.subject} - {self.teacher} - Tiết {self.counter} - {self.schedule_time}"

    def save(self, *args, **kwargs):
        if not self.pk:  # Nếu đây là một tiết học mới
            last_lesson = Lessons.objects.filter(classroom=self.classroom, subject=self.subject).order_by('-counter').first()
            if last_lesson:
                self.counter = last_lesson.counter + 1
        super().save(*args, **kwargs)
        
class LessonReview(models.Model):
    REVIEW_CHOICES = [
        ('A', 'Giỏi'),
        ('B', 'Tốt'),
        ('C', 'Trung Bình'),
        ('D', 'Kém'),
    ]

    lesson = models.ForeignKey(Lessons, on_delete=models.CASCADE)
    review = models.TextField()
    rating = models.CharField(max_length=1, choices=REVIEW_CHOICES)  # Thêm trường xếp loại

    def __str__(self):
        return f"{self.lesson.subject.subject_name} - Review ID: {self.pk} - Rating: {self.rating}"

my_Class/forms.py
from typing import Any
from django import forms
import re 
from django.contrib.auth.models import User
from django.core.exceptions import ObjectDoesNotExist
from .models import *

class RegistrationForm(forms.Form):
    username = forms.CharField(label='Tài Khoản', max_length=50)
    email = forms.EmailField(label='Email')
    password1 = forms.CharField(label='Mật Khẩu', widget=forms.PasswordInput())
    password2 = forms.CharField(label='Nhập Lại Mật Khẩu', widget=forms.PasswordInput())
    def clean_password2(self):
        if 'password1' in self.cleaned_data:
            password1 = self.cleaned_data['password1']
            password2 = self.cleaned_data['password2']
            if password1==password2 and password1:
                return password2
        raise forms.ValidationError('Mật Khẩu không Hợp Lệ')
    def clean_username(self):
        username = self.cleaned_data['username']
        if re.search(r'^\w+s', username):
            raise forms.ValidationError('Tên Tài Khoản Chứa Kí Tự Đặc Biệt')
        try:
            User.objects.get(username=username)
        except ObjectDoesNotExist:
            return username
        raise forms.ValidationError('Tài Khoản Đã Tồn Tại')
    def save(self):
        User.objects.create_user(username=self.cleaned_data['username'], email=self.cleaned_data['email'], password=self.cleaned_data['password2'])
        
class StudentIDForm(forms.Form):
    student_id = forms.IntegerField(
        label='Student ID',
        widget=forms.NumberInput(
            attrs={
                'class': 'form-control',
                'id': 'Student ID',
                'placeholder': 'Enter Student ID',
                'name': 'Student ID'
            }
        )
    )

from django.contrib.auth.forms import AuthenticationForm

class CustomLoginForm(AuthenticationForm):
    username = forms.CharField(
        widget=forms.TextInput(
            attrs={
                'class': 'form-control',
                'id': 'Student ID',
                'placeholder': 'Enter Student ID',
                'name': 'Student ID'
            }
        )
    )
    password = forms.CharField(
        widget=forms.PasswordInput(
            attrs={
                'class': 'form-control',
                'id': 'Password',
                'placeholder': 'Enter Password',
                'name': 'Password'
            }
        )
    )





class ScoreForm_Test(forms.ModelForm):
    class Meta:
        model = Score
        fields = ['student','subject','K1_score', 'K2_score', 'K3_score']
        
class LessonReviewForm(forms.ModelForm):
    class Meta:
        model = LessonReview
        fields = ['lesson', 'review', 'rating']
        widgets = {
            'lesson': forms.Select(attrs={'class': 'form-control'}),
            
        }


class LessonsForm(forms.ModelForm):
    class Meta:
        model = Lessons
        fields = ['classroom', 'subject', 'teacher']

Classroom/views.py
from django.shortcuts import render
from django.http import HttpResponse
from django.template import loader
from .models import *
from .forms import RegistrationForm
from django.http import HttpResponseRedirect
from django.contrib.auth.decorators import login_required

# from django.http import HttpResponseRedirect

# Create your views here.

@login_required(login_url='/login/')
def classroom(request):
    mystudents = Student.objects.all()
    template = loader.get_template('classroom.html')
    context = {
        'myStudents' : mystudents,
    }
    return HttpResponse(template.render(context,request))


def register (request):
  form = RegistrationForm()
  template = loader.get_template('register.html')
  if request.method == 'POST':
    form = RegistrationForm(request.POST)
    if form.is_valid():
      form.save()
      return HttpResponseRedirect('/')
  context = {
    'form': form
  }
  return HttpResponse(template.render(context,request))


def Home(request):
    template = loader.get_template('home.html')
    return HttpResponse(template.render())
  

my_Class/views.py
from django.shortcuts import render,get_object_or_404,redirect
from django.http import HttpResponse
from django.template import loader
from .models import *
from django.utils import timezone
from django.http import HttpResponseRedirect
from django.contrib.auth.decorators import login_required

from datetime import datetime
from .forms import *
from django.contrib.auth.views import LoginView
from django.http import JsonResponse





classroom = Class.objects.get(class_CODE='6A')
# view lớp học
@login_required(login_url='/home/')
def classroom_view(request):
  now = datetime.now()
  class_code = request.session.get('class_code', None)
  subject_code = request.GET.get('subject_code', None)
  # subject_code = request.GET.get('subject_code')
  request.session['subject_code'] = subject_code
  # print(class_code)
  # print(subject_code)
  if subject_code is not None:
    subject = get_object_or_404(Subject, subject_CODE=subject_code)
  else:
    subject = "Chưa lấy được"
    print(request.session.items())
  classroom = Class.objects.get(class_CODE=class_code)
  students = Student.objects.filter(classroom=classroom)
  template = loader.get_template('classroom.html')
  
  if request.method == 'POST':
    form_lession = LessonsForm(request.POST)
    if form_lession.is_valid():
      form_lession.save()
      return redirect('Classroom') 
  else:
    form_lession = LessonsForm()
  if request.method == 'POST':
      form_review = LessonReviewForm(request.POST)
      if form_review.is_valid():
          form_review.save()
          return redirect('Classroom') 
  else:
      form_review = LessonReviewForm()
  context = {
      'class':classroom,
      'Students' : students,
      'current_time':now,
      'subject_code': subject,
      'form_add_lesssion': form_lession,
      'form_review': form_review
  }
  return HttpResponse(template.render(context,request))

#  view đăng kí 
def register_view (request):
  form = RegistrationForm()
  template = loader.get_template('register.html')
  if request.method == 'POST':
    form = RegistrationForm(request.POST)
    if form.is_valid():
      form.save()
      return HttpResponseRedirect('/')
  context = {
    'form': form
  }
  return HttpResponse(template.render(context,request))

def student_detail(request, student_ID):
  # lấy student, lưu vào session
  student = get_object_or_404(Student, pk=student_ID)
  request.session['student_ID'] = student_ID
  # Lấy subject_code từ session
  subject_code = request.session.get('subject_code')
  subject = get_object_or_404(Subject,pk=subject_code)
  # Hiển thị bảng điểm
  scores = Score.objects.filter(student=student,subject =subject_code)
  my_student = Student.objects.get(student_ID=request.session['student_ID'])
  my_subject = Subject.objects.get(subject_CODE=request.session['subject_code'])
  print(my_student)
  print(subject)
  if request.method == 'POST':
      form = ScoreForm_Test(request.POST)
      if form.is_valid():
        try:
          score = form.save(commit=False)
          score.student = my_student
          return redirect('student_detail')  # replace with your success url
        except Exception as e:
          print(f"An error occurred: {e}")
  else:
        form = ScoreForm_Test()
  template = loader.get_template('details.html')
  context = {
    'student': student,
    'scores': scores,
    'form': form
  }
  return HttpResponse(template.render(context,request))



  
class CustomLoginView(LoginView):
  authentication_form = CustomLoginForm

  def get_context_data(self, **kwargs):
      context = super().get_context_data(**kwargs)
      context['form_student_ID'] = StudentIDForm()
      return context
  def post(self, request, *args, **kwargs):
      form = StudentIDForm(request.POST)
      if form.is_valid():
          student_id = form.cleaned_data['student_id']
          return redirect('student_grade_view', student_ID=student_id)
      else:
          return super().post(request, *args, **kwargs)

def student_grade_view(request, student_ID):
  student = get_object_or_404(Student, pk=student_ID)
  scores = Score.objects.filter(student=student)
  template = loader.get_template('student_grade.html')
  context = {
    'student': student, 
    'scores': scores
  }
  return HttpResponse(template.render(context,request))


def week_summary_view(request):
  class_code = request.session.get('class_code', None)
  lessons = Lessons.objects.filter(classroom__class_CODE=class_code)
  reviews = LessonReview.objects.filter(lesson__in=lessons)
  # reviews = LessonReview.objects.all()  # Lấy tất cả đánh giá
  template = loader.get_template('week_summary.html')
  context = {
    'week_review':reviews,
    'class':class_code
  }
  return HttpResponse(template.render(context,request))

  
def option_view(request):
  # xử lí select class and subject
  classes = Class.objects.all()
  subjects = None
  if 'class_code' in request.GET:
    class_code = request.GET.get('class_code')
    try:
      classroom = Class.objects.get(class_CODE=class_code)
      subjects = list(classroom.subjects.values())
      request.session['class_code'] = class_code  
    except Class.DoesNotExist:
      pass
    return JsonResponse(subjects, safe=False)
  else:
    return render(request, 'option.html', {'classes': classes})


def create_lesson_view(request):
    if request.method == 'GET':
        subject_code = request.GET.get('subject_code')
        if subject_code:
            try:
                # Lấy thông tin từ session và request
                teacher_username = request.session.get('username')
                class_code = request.session.get('class_code')

                # Lấy đối tượng từ cơ sở dữ liệu
                teacher = Teacher.objects.get(username=teacher_username)
                classroom = Class.objects.get(class_CODE=class_code)
                subject = Subject.objects.get(subject_CODE=subject_code)

                # Tạo một Lesson mới
                lesson = Lessons(classroom=classroom, subject=subject, teacher=teacher, schedule_time=timezone.now())
                lesson.save()

                return HttpResponse('Lesson created successfully')
            except (Teacher.DoesNotExist, Class.DoesNotExist, Subject.DoesNotExist):
                return HttpResponse('Failed to create lesson: invalid data')
        else:
            return HttpResponse('Failed to create lesson: no subject_code provided')
    else:
        return HttpResponse('Invalid request method')
      


def test_saveScore (request):
  form=ScoreForm_Test()
  template = loader.get_template('test.html')
  if request.method == 'POST':
        form = ScoreForm_Test(request.POST)
        if form.is_valid():
            form.save()
            return redirect('Savescore')
  else:
        form = ScoreForm_Test()
 
  context = {
    'form': form
  }
  return HttpResponse(template.render(context,request))


# input điểm 
def save_score(request):
  template = loader.get_template('details.html')
  student_id = request.session.get('student_ID')
  get_student = get_object_or_404(Student, Student_ID=student_id)
  subject_id = request.session.get('subject_id')
  get_subject = get_object_or_404(Subject, id=subject_id)
  # Kiểm tra xem request có phải là POST không
  if request.method == 'POST':
    form = ScoreForm_Test(request.POST)
    if form.is_valid():
        form.save()
        return redirect('test')
  else:
    form = ScoreForm_Test()
  context = {
    'form': form
  }
  return HttpResponse(template.render(context,request))

my_Class/templates/base.html
{% load static %}
<!DOCTYPE html>

{% comment %} 
đây là file cơ sở dùng để:
tạo các block tĩnh, và block để các file khác kế thừa
{% endcomment %}

<html>
  <head>
      
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <link rel="icon" type="image/x-icon" href="{% static "online-classes-icon-vector-23983367.ico" %}"> 
    <title>{% block title %}{% endblock title %}</title>
    {% load bootstrap5 %}
    {% bootstrap_css %}
    {% bootstrap_javascript %}
    {% comment %} <meta name="description" content=""> {% endcomment %}
    {% comment %} <meta name="viewport" content="width=device-width, initial-scale=1"> {% endcomment %}
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-C6RzsynM9kWDrMNeT87bh95OGNyZPhcTNXj1NW7RuBCsyN/o0jlpcV8Qyq46cDfL" crossorigin="anonymous"></script>

    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.3.1/dist/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.14.7/dist/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.3.1/dist/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>

    <style>
      body {
          margin: 0;
          padding: 0;
          height: 100vh;
          width: 100vw;
          overflow-x: hidden;
      }
      </style>
  </head>
<body style="background-color: #2385C4;">
  {% block Header %}
  <nav class="navbar navbar-expand-lg navbar-dark fixed-top" style="background-color: #11499C">
    <div class="container-fluid">
      
        <div class="collapse navbar-collapse" id="navbarTogglerDemo02">
          <a class="navbar-brand text-white font-weight-bold nav-link active" aria-current="page" style="font-size: 200%" href="/home" >Class 4.0</a>
          <div class="col-sm-9"></div> 
          <div class="col-sm-2 row">
              {% if user.username %}

              <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                <div class="col-sm-6">
                    <p class="text-white text-center" style="height: 100%;
                    line-height: 100%;
                    display: flex;
                    align-items: center;
                    justify-content: center;">{{user.username}}</p>
                </div>
                <div class="col-sm-6">    
                    <li class="nav-item">
                      <a href="{% url 'logout' %}" class="nav-link btn btn-primary text-white">Logout</a>
                    </li>
                </div>  
              
              </ul>
              {% else %}
                <a href = "/home" class="text-white btn btn-primary">Home</a>
              {% endif %}
          </div>
        </div>
        
    </div>
  </nav>
  {% endblock Header %}
  

<div class="container-fluid" style="margin-top: 80px;">
  {% block content %} {% endblock content %}
</div>

  </body>
</html>

my_Class/templates/classroom.html
{% extends "base.html" %}
{% block title %}Classroom{% endblock title %}

{% comment %}
2
file này hiển thị sơ đồ lớp học và các tính năng chính của web
- Xem thông tin học sinh
-Xếp loại tiết hoc
-
{% endcomment %}

{% block content %}



<div class="container-fluid" style="margin-top: 5%; ">
  <div class="container-fluid row">
    {% comment %} <div class="col-sm-1"></div> {% endcomment %}
    <div class="col-sm-8">
      <div style="  margin-bottom: 10px" class="row">
        <div class="container" style="margin-top: 10px">
          <div class="row">
            <div class="col">
              <div class="container overflow-hidden">
                <div class="row">
                  <div class="col-3">
                    <div class="p-3 border bg-light text-center d-flex align-items-center justify-content-center font-weight-bold" style="border-radius: 10px; height: 60px">{{ class.class_CODE }}</div>
                  </div>
                  <div class="col-3">
                    <div class="p-3 border bg-light text-center d-flex align-items-center justify-content-center font-weight-bold" style="border-radius: 10px; height: 60px">{{subject_code.subject_name}}</div>
                  </div>  
                </div>
              </div>
            </div>
          </div>
        </div>
        
      </div>
        <div class="card" style="margin-top: 2%; margin-bottom: 1%">
          <div class="card-body">
            <h5 class="card-title">Sơ Đồ Lớp</h5>
            <div class="row row-cols-4" style="margin-top: 2% margin-bottom: 2%">
                <tbody >
                    {% for student in Students %}
                    <div class="col-sm-3 mb-3">
                        <div class="card border-primary">
                            <div class="card-body text-center d-flex align-items-center justify-content-center" style="margin-top: 2%; margin-bottom: 1%">
                                <a href="{% url 'student_detail' student.student_ID %}" class="text-white btn btn-primary text-truncate" style="font-size: 1em">{{ student.student_name }}</a>
                            </div>
                          </div>
                      </div>
                    {% endfor %}
                </tbody>
          </div> 
          </div>

        </div>
        
    </div>
    <div class="col-sm-4">
      <div class="card display-5" style="margin-top: 10px">
        <div class="card-body" style="height: 60px">
          <p class="text-Blue text-center" style="font-size: 20px; ">{{ current_time }}</p>
        </div>
      </div>

      <div class="card display-5" style="margin-top: 4%;margin-bottom:5%; background-color: #07478D">
        <div class="card-body row" style="height: 5%">
          <div class="col-12">
            <button type="submit" class="btn text-white font-weight-bold" value="Chọn" style="transform: scale(0.9); width:50%;margin-left: auto; margin-right: auto; display: block; font-size: 0.5em; border-radius: 10px; background-image: linear-gradient(to right, #126DBC, #8C52FF);border: none;">Bắt đầu tiết học</button>                
            
            <form method="post" style="margin-bottom: 5%">
              <h2 class="card-title text-white" style="margin-top: 2%;font-size:0.5em">Nhập thông tin</h2>
              {% csrf_token %}
              <table class="table" method="post" style="font-size:0.35em; border-radius: 10px;">
                <thead>
                  <tr>
                      <th scope="col">#</th>
                      <th scope="col">Thông tin</th>
                  </tr>
                </thead>
                <tbody>
                  <tr>
                      <th scope="row">Lớp</th>
                      <td>
                        {{ form_add_lesssion.classroom }}
                      </td>
                  </tr>

                  <tr>
                      <th scope="row">Môn học</th>
                      <td>        
                        {{ form_add_lesssion.subject }}
                      </td>
                  </tr>

                  <tr>
                      <th scope="row">Giáo viên</th>
                      <td>        
                        {{ form_add_lesssion.teacher }}
                      </td>
                  </tr>

                  <tr>
                      <th scope="row">Thời gian</th>
                      <td>        
                        {{ form_add_lesssion.schedule_time }}
                      </td>
                  </tr>

                </tbody>
              </table> 
              <button type="submit" class="btn btn-primary" style="transform: scale(0.7); width:40%;margin-left: auto; margin-right: auto; display: block; font-size: 0.5em; border-radius: 30px; background-image: linear-gradient(to right, #126DBC, #8C52FF);border: none;">Submit</button>
            </form>

            <div style="margin-bottom: 5%">
              <h2 class="card-title text-white" style="margin-top: 2%;font-size:0.5em">Chấm điểm</h2>
              <div class="card">
                <a href="{% url 'Savescore' %}" type="submit" class="btn btn-primary" style="transform: scale(0.7); width:50%;margin-left: auto; margin-right: auto; display: block; font-size: 0.5em; border-radius: 15px; background-image: linear-gradient(to right, #126DBC, #8C52FF);border: none;">Nhập bảng điểm</a>
              </div>
            </div>

            <form method="post">
              <h2 class="card-title text-white" style="margin-top: 2%;font-size:0.5em">Đánh giá tiết học</h2>
              {% csrf_token %}
              <table class="table" method="post" style="font-size:0.35em; border-radius: 10px;">
                <thead>
                  <tr>
                      <th scope="col">#</th>
                      <th scope="col">Nội dung</th>
                  </tr>
                </thead>
                <tbody>
                  
                    <th scope="row">Lession</th>
                    <td>
                      {{ form_review.lesson }}
                    </td> 
                </tr>
                  <tr>
                      <th scope="row">Nhận xét</th>
                      <td>
                        {{ form_review.review }}
                      </td>
                  </tr>

                  <tr>
                      <th scope="row">Đánh giá</th>
                      <td>        
                        {{ form_review.rating }}
                      </td>
                  </tr>
                </tbody>
              </table> 
              <button type="submit" class="btn btn-primary" style="transform: scale(0.7); width:40%;margin-left: auto; margin-right: auto; display: block; font-size: 0.5em; border-radius: 30px; background-image: linear-gradient(to right, #126DBC, #8C52FF);border: none;">Submit</button>
            </form>

          </div>
        </div>
      </div>
    </div>

  </div>

</div>


{% endblock %}


      
    
    

my_Class/templates/register.html
{% extends "base.html" %}
{% block title %}Register{% endblock title %}
{% comment %} block này Tiến phát triển để quản trị {% endcomment %}

{% block content %}
<center>
    <form action='.' method='POST'>
      {% csrf_token %}
      {{form.as_p}}
      <input type="Submit" value="Đăng Kí"/>
    </form>
    <p>Back to <a href="/">Home</a></p>
  </center>

{% endblock content %}

my_Class/templates/week_summary.html
{% extends "base.html" %}
{% load static %}
{% block title %}Student_grade{% endblock title %}

{% comment %}
5
- Hiển thị điểm các môn của học sinh 
{% endcomment %}

{% block content %}
    <div class="row"> 
        <div class="col-1"></div>
    
        <div class="col-10">
            <div class="card">
                <h3 class="card-title text-center">Thông tin lớp</h3>
                <div class="card-body">   
                    <table class="table">
                        <tbody>
                        <tr>
                            <th class="display-6 font-weight-bold" style="font-size: 1.2em" scope="row">Lớp</th>
                            <td class="display-6 font-weight-bold" style="font-size: 1.2em">{{class}}</td>
                        </tr>

                        </tbody>
                    </table>
                </div>    
            </div>
        </div> 
        <div class="col-1"></div>   
    </div>
    
    <div class="row" style="margin-top: 1%">
        <div class="col-1"></div>
        <div class="col-10">
            <div class="card" style="background-color: #07478D">
                <div class="card-body">
                    <h2 class="card-title text-white" style="margin-top: 2%;">Tổng kết tuần</h2>
                    <table class="table">
                        <thead>
                        <tr>
                            <th scope="col">Môn</th>
                            <th scope="col">Nhận xét</th>
                            <th scope="col">Xếp loại</th>
                        </tr>
                        </thead>
                        <tbody>
                        {% for review in week_review %}
                        <tr>
                            <th scope="row">{{ review.lesson.subject.subject_name }}</th>
                            <td>{{ review.review }}</td>
                            <td>{{ review.get_rating_display }}</td>
                        </tr>
                        {% endfor %}
    
                        </tbody>
                    </table>
                </div>
            </div>
        </div> 
        <div class="col-1"></div>   
    </div>
{% endblock content %}